name: "jarvis"
author: "Dipjyoti Metia" 
description: "automated github actions"
branding:
  icon: 'award'  
  color: 'green'
inputs:
  GITHUB_TOKEN:  
    description: 'A GitHub personal access token used to perform actions.'
    required: true
  GITHUB_REPOSITORY:  
    description: 'The github repository name.'
    required: true
  OWNER:  
    description: 'Owner of the repository.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
   - ${{ inputs.GITHUB_TOKEN }}
   - ${{ inputs.GITHUB_REPOSITORY }}
   - ${{ inputs.OWNER }}
    